x-airflow-common:
  &airflow-common
  image: apache/airflow:2.8.1
  env_file: .env

  environment:
    &airflow-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"


services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data


  redis:
    image: redis:7

  airflow-webserver:
    <<: *airflow-common
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dags:/opt/airflow/dags
    command: webserver
    ports:
      - "8080:8080"

  airflow-scheduler:
    <<: *airflow-common
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dags:/opt/airflow/dags
    command: scheduler

  airflow-worker:
    image: asia-southeast1-docker.pkg.dev/earthquake-etl/etl-docker-repo/airflow_custom_worker:v1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dags:/opt/airflow/dags
    command: celery worker


  airflow-init:
    <<: *airflow-common
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dags:/opt/airflow/dags
    command: bash -c "airflow db migrate && airflow users create \
      --username admin --password admin --firstname Admin --lastname User \
      --role Admin --email admin@example.com"

  airflow-cli:
    <<: *airflow-common
    entrypoint: ""
    command: bash
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dags:/opt/airflow/dags
    tty: true 

volumes:
  postgres-db-volume:
